# Generated by Django 4.0 on 2024-07-06 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_book_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
