# Generated by Django 4.0 on 2024-05-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_author_book_rating_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
