# Generated by Django 4.0 on 2024-06-30 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_customuser_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_genres',
            field=models.TextField(blank=True, null=True),
        ),
    ]
